name: Build and Deploy to Cloud Run using Github Container Registry

on:
  workflow_dispatch:

env:
  PROJECT_ID: stockbot-432823
  SERVICE: stockbotapi
  REGION: europe-west1
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}/stockbotapi

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and Push Docker Image to GitHub Container Registry
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }}:${{ github.sha }} .
          docker push ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

     

      # Authenticate to Google Cloud (for deployment)
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # Deploy to Cloud Run using Github Container Registry
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          env_vars: |
            DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }},
            FMP_API_KEY=${{ secrets.FMP_API_KEY }},
            AV_API_KEY=${{ secrets.AV_API_KEY}},
            AUX_API_KEY=${{ secrets.AUX_API_KEY }},
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}

      # Output the Cloud Run service URL
      - name: Show Cloud Run Service URL
        run: echo ${{ steps.deploy.outputs.url }}
